cabsharing/accounts/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

 
app_name='accounts'

urlpatterns=[
    path('signup/', views.SignupView, name='user_signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='user_logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change_form.html') , name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
                                                                email_template_name='accounts/password_reset_email.html',
                                                                subject_template_name='accounts/password_reset_subject.txt')
                                                                                    ,name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
# normal urls are not working in my case

    re_path(r'^(?P<pk>\d+)/detail/$', views.UserDetailView.as_view(), name='user_detail'),
    # re_path(r'^(?P<pk>\d+)/delete/$', views.UserDeleteView.as_view(template_name='accounts/user_delete.html'), name='user_delete'),

    re_path(r'^(?P<pk>\d+)/update/$', views.UserUpdateView.as_view(), name='user_update'),


    # re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabsharing/bookings/urls.py
from django.urls import path, re_path, include
from bookings import views
from django.conf.urls.static import static
from django.conf import settings

app_name='bookings'

urlpatterns=[
    path('create/', views.create_booking, name='bookings_create'),
    re_path(r'^(?P<pk>\d+)/update/$', views.update_booking, name='bookings_update'),

    # re_path(r'^(?P<pk>\d+)/update/$', views.BookingUpdateView.as_view(template_name='bookings/bookings_update.html'), name='bookings_update'),
    re_path(r'^(?P<pk>\d+)/delete/$', views.BookingDeleteView.as_view(template_name='bookings/bookings_delete.html'), name='bookings_delete'),
    re_path(r'^(?P<pk>\d+)/join/$', views.join_group , name='group_join'),
    re_path(r'^(?P<pk>\d+)/leave/$', views.leave_group , name='group_leave'),
    re_path(r'^(?P<pk>\d+)/info/$', views.GroupInfo.as_view(template_name='bookings/bookings_detail.html'), name='group_info'),
    # re_path(r'^(?P<pk>\d+)/chats/$', views.MessageDisplayView.as_view(template_name='bookings/chats_list.html'), name='chats_display'),
    re_path(r'^(?P<pk>\d+)/chats/$', views.message_create, name='chats_display'),
    path('mybookings/', views.my_bookings, name='my_bookings'),
    # re_path(r'^(?P<pk>\d+)/my_bookings/$', views.mybooking, name='mybooking'),
    path('feedback/', views.feedback, name='feedback'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

cabsharing/cabsharing/urls.py
from django.contrib import admin
from django.urls import path, include
from bookings import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('' , views.filter, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bookings/', include('bookings.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabsharing/bookings/forms.py
from django import forms
from bookings.models import Booking, Member, Chat, Feedback

GENDER=[
    ('-','-'),
    ('all','all'),
    ('girls only','girls only'),
    ('boys only', 'boys only')
]


 
class BookingForm(forms.ModelForm):
    start_position=forms.CharField(label='From:', required=True)
    destination=forms.CharField(label='To:', required=True)
    date=forms.DateField(label='Date:' ,required=True,widget=forms.DateInput(attrs={'placeholder':'yyyy-mm-dd'}))
    time=forms.TimeField(label='Time:',required=True, widget=forms.TimeInput(attrs={'placeholder':'00:00'}), help_text='24-hours format')
    max_members=forms.IntegerField(label='Maximum number of members:', help_text='maximum number of members includes you as well.', required=True)
    gender=forms.ChoiceField(label='Group open to:', choices=GENDER )
    description=forms.CharField(label='Description:', required=False)

    class Meta():
        model=Booking
        fields=['start_position' ,'destination','date','time', 'max_members','gender', 'description']


class MemberForm(forms.ModelForm):

    class Meta():
        model=Member
        fields=[]


class MessageForm(forms.ModelForm):
    message=forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'Type a message'}))
    class Meta():
        model=Chat
        fields=['message']



class FilterForm(forms.Form):
    start_position=forms.CharField(label='From:', required=False)
    destination=forms.CharField(label='To:', required=False )
    date=forms.DateField(label='Date:' ,required=False ,widget=forms.DateInput(attrs={'placeholder':'yyyy-mm-dd'}),)
    time=forms.TimeField(label='Time:',required=False, widget=forms.TimeInput(attrs={'placeholder':'00:00'}), help_text='24-hours format')
    gender=forms.ChoiceField(label='Group open to:', choices=GENDER ,required=False)


class FeedbackForm(forms.ModelForm):
    feedback=forms.CharField(widget=forms.Textarea)
    class Meta():
        model=Feedback
        fields=['feedback']

cabsharing/bookings/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView , ListView, UpdateView , DeleteView, DetailView
from bookings.models import Booking, Member, Chat, Feedback
from bookings.forms import BookingForm, MemberForm, MessageForm, FilterForm, FeedbackForm
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from accounts.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.http import Http404
from django.contrib import messages
import datetime
from django.utils import timezone
# from datetime import timedelta
# Create your views here.
 
# User=get_user_model()
# class BookingCreateView(LoginRequiredMixin, CreateView):
#     model=Booking
#     form_class=BookingForm
#     success_url=reverse_lazy('index')
#
#     def form_valid(self, form):
#         form.instance.creator = self.request.user
#         return super().form_valid(form)
#
#     def save(self, *args, **kwargs):
#         if (self.gender == 'boys only' and (self.hostel=='Subhansiri' or self.hostel=='Dhansiri')):
#             messages.success(self.request, "A girl can't chose only boys option!")
#             return redirect('bookings:bookings_create')
#         elif (self.gender == 'girls only' and (not(self.hostel=='Subhansiri' or self.hostel=='Dhansiri'))):
#             messages.success(self.request, "A boy can't chose only girls option!")
#             return redirect('bookings:bookings_create')
#         else:
#             super().save(*args, **kwargs)
@login_required
def create_booking(request):
    if request.method=='POST':
        form=BookingForm(request.POST)
        if form.is_valid():
            booking=form.save(commit=False)

            if(booking.gender=='boys only'):
                if(request.user.userprofile.hostel=='Subhansiri' or request.user.userprofile.hostel=='Dhansiri'):
                    # messages.add_message(request, "A girl can't chose only boys option")
                    messages.success(request, "A girl can't chose <strong>only boys</strong> option")
                    return redirect('bookings:bookings_create')

            if(booking.gender=='girls only'):
                if(not(request.user.userprofile.hostel=='Subhansiri' or request.user.userprofile.hostel=='Dhansiri')):
                    # messages.add_message(request, "A girl can't chose only boys option")
                    messages.success(request,  "A boy can't chose <strong>only girls</strong> option")
                    return redirect('bookings:bookings_create')

            if(booking.date <datetime.date.today()):
                messages.success(request,  "You can't create a booking with a date which has already passed.")
                return redirect('bookings:bookings_create')

            booking.user=request.user
            booking.creator=request.user.username
            booking.save()
            messages.success(request,  "Booking created successfully ")
            return redirect('index')
    else:
        form=BookingForm()
        return render(request, 'bookings/bookings_form.html', {'form':form})


class BookingUpdateView(LoginRequiredMixin, UpdateView):
    model=Booking
    form_class=BookingForm
    success_url=reverse_lazy('index')


def update_booking(request, pk):
    if request.method=='POST':
        form=BookingForm(request.POST)
        if form.is_valid():
            form=form.save(commit=False)

            if(form.gender=='boys only'):
                if(request.user.userprofile.hostel=='Subhansiri' or request.user.userprofile.hostel=='Dhansiri'):
                    # messages.add_message(request, "A girl can't chose only boys option")
                    messages.success(request, "A girl can't chose <strong>only boys</strong> option")
                    return redirect('bookings:bookings_update' ,pk=pk)

            if(form.gender=='girls only'):
                if(not(request.user.userprofile.hostel=='Subhansiri' or request.user.userprofile.hostel=='Dhansiri')):
                    # messages.add_message(request, "A girl can't chose only boys option")
                    messages.success(request,  "A boy can't chose <strong>only girls</strong> option")
                    return redirect('bookings:bookings_update' ,pk=pk)

            if(form.date <datetime.date.today()):
                messages.success(request,  "You can't update a booking with a date which has already passed.")
                return redirect('bookings:bookings_update' ,pk=pk)

            # booking=get_object_or_404(Booking, pk=pk)     //this created a new booking.
            booking=Booking.objects.get(pk=pk)
            booking.start_position=form.start_position
            booking.destination=form.destination
            booking.date=form.date
            booking.time=form.time
            booking.max_members=form.max_members
            booking.gender=form.gender
            booking.description=form.description
            booking.save()
            messages.success(request,  "Booking updated successfully ")
            return redirect('index')
    else:
        context={}
        obj=get_object_or_404(Booking, pk=pk)
        form=BookingForm( instance=obj)



        context['form']=form
        return render (request, "bookings/bookings_update.html", context)
    #
    # def save(self, *args, **kwargs):
    #     if (self.gender == 'boys only' and (self.hostel=='Subhansiri' or self.hostel=='Dhansiri')):
    #         messages.success(self.request, "A girl can't chose only boys option!")
    #         return redirect('bookings:bookings_update', pk=self.kwargs['pk'])
    #     elif (self.gender == 'girls only' and (not(request.user.userprofile.hostel=='Subhansiri' or request.user.userprofile.hostel=='Dhansiri'))):
    #         print('hehehe')
    #         messages.success(self.request, "A boy can't chose only girls option!")
    #         return redirect('bookings:bookings_update', pk=self.kwargs['pk'])
    #     else:
    #         super().save(*args, **kwargs)

class BookingDeleteView(LoginRequiredMixin, DeleteView):
    model=Booking
    success_url=reverse_lazy('index')
    success_message='Booking has been deleted'
    def delete(self, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(*args,**kwargs)

# class BookingListView( ListView):
#     model=Booking
#     context_object_name='bookings_list'

    # def get_queryset(self):
    #     booking= Booking.objects.order_by('date')
    #     return booking.order_by('time')

@login_required
def my_bookings(request):
    context={}
    hehehe=[]
    context['mybooking']=Booking.objects.all().filter(creator__iexact=request.user.username).reverse()
    for booking in Booking.objects.all():
        for member in booking.members.all():
            if request.user.username == member.name:
                hehehe.append(booking)
    context['memberbooking']=hehehe
    return render(request, 'bookings/mybookings.html', context)


class GroupInfo(DetailView):
    model=Booking
    context_object_name='booking'
########################################################################################################
########################################################################################################


@login_required
def join_group(request, pk):
    booking=get_object_or_404(Booking, pk=pk)
    if request.method=='POST':
        form=MemberForm(request.POST)
        if form.is_valid():
            persons=booking.members.all()
            for person in persons:
                if(request.user.username == person.name):
                    messages.success(request,  "You are already a member of this Booking ")
                    return redirect('index')

            if (request.user.username==booking.creator):
                messages.success(request,  "You are already a member of this Booking ")
                return redirect('index')

            if(booking.gender=='boys only'):
                if(request.user.userprofile.hostel=='Subhansiri' or request.user.userprofile.hostel=='Dhansiri'):
                    messages.success(request,  "Girls can't join <strong>boys only</strong> bookings")
                    return redirect('index')

            if(booking.gender=='girls only'):
                if(request.user.userprofile.hostel=='Subhansiri' or request.user.userprofile.hostel=='Dhansiri'):
                    member=form.save(commit=False)
                    member.booking=booking
                    member.user=request.user
                    member.name=request.user.username
                    member.save()
                    messages.success(request,  "<strong> Booking </strong> joined successfully!")
                    return redirect('index')
                else:
                    messages.success(request,  "Boys can't join <strong> girls only </strong> bookings")
                    return redirect('index')


            member=form.save(commit=False)
            member.booking=booking
            member.user=request.user
            member.name=request.user.username
            member.save()
            messages.success(request,  "<strong> Booking </strong> joined successfully!")
            return redirect('index')


    else:
        form=MemberForm()
    return render(request, 'bookings/joining_form.html', {'form':form})



@login_required
def leave_group(request, pk):
    booking=get_object_or_404(Booking, pk=pk)
    if request.method=='POST':
        form=MemberForm(request.POST)
        if form.is_valid():
            try:
                member=booking.members.get(name=request.user.username)
                member.delete()
                messages.success(request,  "Booking left successfully! ")
                return redirect('index')

cabsharing/templates/bookings/bookings_base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <!-- <link href="https://fonts.googleapis.com/css?family=Monoton&display=swap" rel="stylesheet"> -->

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- <link href="jquery.datetimepicker.min.css" rel="stylesheet"/> -->
  <title>{% block title %}{% endblock %}</title>
  <style type="text/css">
    #no_booking{
      align: center;
      left: 50%;
    }
  </style>
</head>

<body>

  <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand"  style="font-family:'Monoton', cursive; font-size:1.2em;" href="{% url 'index' %}">CAB SHARING</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class='navbar-nav mx-auto'>
      <li class="nav-item active"><a class="nav-link" href="{% url 'bookings:bookings_create' %}">Create</a></li>
      {% if user.is_authenticated %}
      <li class="nav-item active"><a class="nav-link" href="{% url 'bookings:my_bookings' %}">myBookings</a></li>
      {% endif %}
    </ul>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'bookings:feedback' %}">Feedback<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{user.username}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:user_detail' pk=user.pk %}">Profile</a>
            <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Logout</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:user_logout' %}">Logout<span class="sr-only">(current)</span></a>
        </li>

        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:user_login' %}">Login<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:user_signup' %}">Sign Up<span class="sr-only">(current)</span></a>
        </li>

        {% endif %}
      </ul>

    </div>
  </nav>

  {% block content %}
  {% endblock %}



  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>
<!-- font-family: 'Monoton', cursive; -->

cabsharing/templates/bookings/bookings_delete.html
{% extends 'bookings/bookings_base.html' %}

{% block title %}
Delete
{% endblock %}



{% block content %}
<div class="container" style='width:30rem background-color:rgb() ;'>
  <form  method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete this booking?</h3>
    <input type="submit" value="Delete" class='btn btn-danger btn-lg'>

  </form>

</div>

{% endblock %}

cabsharing/templates/bookings/bookings_detail.html
{% extends 'bookings/bookings_base.html' %}
{% block title %}
Group Info
{% endblock %}



{% block content %}

<br><br>
<div class="container">

  <div class="card text-white border-secondary mx-auto mb-5 " style='background-color:rgb(145, 0, 61); width:30rem'>
    <div class="card-body">
      <div class="card-title text-center mx-auto">

      </div>
      <div class="card-text">
        <h4>From : {{booking.start_position}}</h4>
        <h4>To : {{booking.destination}}</h4>
        <h4>Date : {{booking.date}}</h4>
        <h4>Time : {{booking.time}}</h4>
        <h4>Group-Admin : {{booking.creator}}</h4>
        <h4>No. of Members : {{booking.members.count|add:"1"}}<small> /{{booking.max_members}}</small></h4>
        <h4>Max no. of Members : {{booking.max_members}}</h4>
        <h4>Group open to: {{booking.gender}}</h4>

        <br>
        <div class="card-link">
          {% if user.username == booking.creator %}
          <a href="{% url 'bookings:bookings_update' pk=booking.pk %}" class='btn btn-warning btn-sm '>Edit</a>
          <a href="{% url 'bookings:bookings_delete' pk=booking.pk %}" class='btn btn-danger btn-sm '>Delete</a>
          {% else %}
                    {% if booking.members.count|add:"1" < booking.max_members %}
                    <a href="{% url 'bookings:group_join' pk=booking.pk %}" class="btn btn-success btn-sm">Join</a>
                    {% else %}
                    <a href="{% url 'bookings:group_join' pk=booking.pk %}" class="btn btn-success btn-sm disabled">Join</a>
                    {% endif %}
                    <a href="{% url 'bookings:group_leave' pk=booking.pk %}" class='btn btn-info btn-sm'>Leave</a>
          {% endif %}

          <a href="{% url 'bookings:group_info' pk=booking.pk %}" class='btn btn-secondary btn-sm'>Info</a>
          <a href="{% url 'bookings:chats_display' pk=booking.pk %}" class='btn btn-primary btn-sm'>Chat</a>

        </div>
      </div>
    </div>
  </div>

  <div class="text-center">
    <h6>Description: {{booking.description}}</h6>
<br>
    <h3>Group Admin: <a href="{% url 'accounts:user_detail' pk=booking.user.pk %}">{{booking.creator}}</a></h3>
    <br>
    <h3>Other Group Members:</h3>
      {% for member in booking.members.all %}
      <h3><a href="{% url 'accounts:user_detail' pk=member.user.pk %}">{{member.name}}</a></h3>

      {% endfor %}

  </div>



</div>

{% endblock %}

cabsharing/templates/bookings/bookings_list.html
{% extends 'bookings/bookings_base.html' %}

{% block title %}
HomePage
{% endblock %}



{% block content %}

<br>
{% if messages %}
{% for message in messages %}
<div class="container">
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
{% endfor %}
{% endif %}

<br><br>
<div class="col-md-9">

  <div class="container">
    <div class="row">
      <div class="card-group ">
        <!-- <div class="col-md-4"> -->
        {% for booking in bookings_list %}

        <div class="col-md-6">

          <!-- {% if user.is_member %}
          sjfhskjhf
          {% endif %}

          {% if request.user in booking.members.all %}
          hahahahahah
          {% endif %} -->




          {% if user.username == booking.creator %}
          <div class="card text-white border-secondary mx-auto mb-5 w-100" style='background-color:rgb(23, 38, 87); '>
            {% else %}
            <div class="card text-white border-secondary mx-auto mb-5 w-100" style='background-color:rgb(23, 38, 87); '>
              {% endif %}
              <div class="card-body" style='border: 1px solid rgb(23, 38, 87) '>
                <div class="card-title text-center">

                </div>
                <div class="card-text">
                  <h6>From : {{booking.start_position}}</h6>
                  <h6>To : {{booking.destination}}</h6>
                  <h6>Date : {{booking.date|date:'d-m-Y'}}</h6>
                  <h6>Time : {{booking.time}}</h6>
                  <h6>Group-Admin : {{booking.creator}}</h6>
                  <h6>No. of Members : {{booking.members.count|add:"1"}}<small style='text-muted'> /{{booking.max_members}}</small></h6>
                  <h6>Group open to: {{booking.gender}}</h6>
                  <br>
                  <div class="card-link">
                    {% if user.username == booking.creator %}
                    <a href="{% url 'bookings:bookings_update' pk=booking.pk %}" class='btn btn-warning btn-sm '>Edit</a>
                    {% endif %}
                    {% if user.username == booking.creator %}
                    <a href="{% url 'bookings:bookings_delete' pk=booking.pk %}" class='btn btn-secondary btn-sm '>Delete</a>
                    {% endif %}
                    {% if booking.members.count|add:"1" < booking.max_members %}
                    <a href="{% url 'bookings:group_join' pk=booking.pk %}" class="btn btn-success btn-sm">Join</a>
                    {% else %}
                    <a href="{% url 'bookings:group_join' pk=booking.pk %}" class="btn btn-success btn-sm disabled">Join</a>
                    {% endif %}
                    <a href="{% url 'bookings:group_leave' pk=booking.pk %}" class='btn btn-info btn-sm'>Leave</a>
                    <a href="{% url 'bookings:group_info' pk=booking.pk %}" class='btn btn-primary btn-sm'>Info</a>
                    <a href="{% url 'bookings:chats_display' pk=booking.pk %}" class='btn btn-sm' style='color:rgb(0, 121, 107);'>Chat</a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {% endfor %}
        </div>
      </div>
    </div>


  </div>

  {% if bookings_list.count == 0 %}
<nav class="navbar  fixed-bottom navbar-expand-lg navbar-dark bg-dark">
  {% endif %}



    <div class="container-fluid" style='background-color:  rgb(28, 26, 27);'>
      <div class="row">
        <div class="col-md-3" style='border-right:1px solid rgb(62, 63, 64)'>
          <h5 style='color:rgb(176, 172, 175);'>IIT Guwahati</h5>
          <a href="http://www.iitg.ac.in/" style="color:rgb(227, 228, 230)">IIT Guwahati</a>
          <br>
        </div>
        <div class="col-md-6" style="border-right:1px solid rgb(62, 63, 64)">
          <h5 class='text-center' style='color:rgb(176, 172, 175); align:center;'>Contact Us</h5>
          <div class="row">
            <div class="col-6 " style="color:rgb(227, 228, 230)">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim</p>
            </div>
            <div class="col-6 " style="color:rgb(227, 228, 230)">
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim</p>

            </div>
          </div>
          <br>
        </div>
        <div class="col-md-3" style='align:right;'>
          <h5 style='color:rgb(176, 172, 175)'>Follow Us</h5>
          <a href="https://www.iitg.ac.in/stud/gymkhana/technical/home/CodingHome.html" style="color:rgb(227, 228, 230)">Coding Club</a><br>
          <a href="https://www.facebook.com/codingclubiitg/" style="color:rgb(227, 228, 230)">facebook</a>
        </div>
      </div>

    </div>

    {% if bookings_list.count == 0 %}
  </nav>
    {% endif %}


  {% endblock %}

cabsharing/templates/bookings/filter.html
{% extends 'bookings/bookings_base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<br><br><br>
<div class="container">
  <div class="card">

    <div class="card-body">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-success btn-lg">Filter</button>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}