cabsharing/accounts/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

 
app_name='accounts'

urlpatterns=[
    path('signup/', views.SignupView, name='user_signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='user_logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change_form.html') , name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
                                                                email_template_name='accounts/password_reset_email.html',
                                                                subject_template_name='accounts/password_reset_subject.txt')
                                                                                    ,name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
# normal urls are not working in my case

    re_path(r'^(?P<pk>\d+)/detail/$', views.UserDetailView.as_view(), name='user_detail'),
    # re_path(r'^(?P<pk>\d+)/delete/$', views.UserDeleteView.as_view(template_name='accounts/user_delete.html'), name='user_delete'),

    re_path(r'^(?P<pk>\d+)/update/$', views.UserUpdateView.as_view(), name='user_update'),


    # re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabsharing/bookings/urls.py
from django.urls import path, re_path, include
from bookings import views
from django.conf.urls.static import static
from django.conf import settings

app_name='bookings'

urlpatterns=[
    path('create/', views.create_booking, name='bookings_create'),
    re_path(r'^(?P<pk>\d+)/update/$', views.update_booking, name='bookings_update'),

    # re_path(r'^(?P<pk>\d+)/update/$', views.BookingUpdateView.as_view(template_name='bookings/bookings_update.html'), name='bookings_update'),
    re_path(r'^(?P<pk>\d+)/delete/$', views.BookingDeleteView.as_view(template_name='bookings/bookings_delete.html'), name='bookings_delete'),
    re_path(r'^(?P<pk>\d+)/join/$', views.join_group , name='group_join'),
    re_path(r'^(?P<pk>\d+)/leave/$', views.leave_group , name='group_leave'),
    re_path(r'^(?P<pk>\d+)/info/$', views.GroupInfo.as_view(template_name='bookings/bookings_detail.html'), name='group_info'),
    # re_path(r'^(?P<pk>\d+)/chats/$', views.MessageDisplayView.as_view(template_name='bookings/chats_list.html'), name='chats_display'),
    re_path(r'^(?P<pk>\d+)/chats/$', views.message_create, name='chats_display'),
    path('mybookings/', views.my_bookings, name='my_bookings'),
    # re_path(r'^(?P<pk>\d+)/my_bookings/$', views.mybooking, name='mybooking'),
    path('feedback/', views.feedback, name='feedback'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

cabsharing/cabsharing/urls.py
from django.contrib import admin
from django.urls import path, include
from bookings import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('' , views.filter, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bookings/', include('bookings.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabsharing/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
HOSTELS=[
        ('Brahmaputra', 'Brahmaputra'),
        ('Dihing', 'Dihing'),
        ('Manas', 'Manas'),
        ('Lohit', 'Lohit'),
        ('Dhansiri', 'Dhansiri'),
        ('Kapili', 'Kapili'),
        ('Siang', 'Siang'),
        ('Kameng', 'Kameng'),
        ('Umiam', 'Umiam'),
        ('Barak', 'Barak'),
        ('Subhansiri', 'Subhansiri'),
        ('Disang/Dibang', 'Disang/Dibang'),
]

   
class UserProfile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    hostel=models.CharField(blank=False, max_length=50 ,choices=HOSTELS)
    profile_pic=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')
    # add any gender-neutral photo in default


    def __str__(self):
        return self.user.username

    # def get_absolute_url(self):
    #     return reverse('accounts:user_detail' , kwargs={'pk':self.pk})

cabsharing/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

HOSTELS=[
        ('Brahmaputra', 'Brahmaputra'),
        ('Dihing', 'Dihing'),
        ('Manas', 'Manas'),
        ('Lohit', 'Lohit'),
        ('Dhansiri', 'Dhansiri'),
        ('Kapili', 'Kapili'),
        ('Siang', 'Siang'),
        ('Kameng', 'Kameng'),
        ('Umiam', 'Umiam'),
        ('Barak', 'Barak'),
        ('Subhansiri', 'Subhansiri'),
        ('Disang/Dibang', 'Disang/Dibang'),
]

 
def emailcheck(value):
    if(value[-11::]!='@iitg.ac.in'):
        raise forms.ValidationError("You must use email-id provided by IIT-Guwahati.")

class UserForm(forms.ModelForm):
    username=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    email=forms.EmailField(widget=forms.TextInput(attrs={'placeholder':'Email'}), validators=[emailcheck])
    class Meta():
        model=User
        fields=('username','email','password')

# def clean_email(self):
#     email=self.cleaned_data['email']
#     if(email(11,))

class UserProfileForm(forms.ModelForm):

    hostel=forms.ChoiceField(required=True, choices=HOSTELS)

    class Meta():
        model=UserProfile
        fields=('hostel', 'profile_pic')

cabsharing/accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import login, authenticate
from .forms import UserProfileForm, UserForm
from django.views.generic import DetailView, DeleteView, UpdateView
from django.contrib.auth.models import User
from accounts.models import UserProfile
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


def SignupView(request):
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileForm(data=request.POST)

        if(user_form.is_valid() and profile_form.is_valid()):
            user=user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            username=user_form.cleaned_data['username']
            password=user_form.cleaned_data['password']

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic'] #may try if else to attach default

            profile.save()

            user=authenticate(username=username , password=password)
            login(request, user)
            return redirect('index')
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form=UserForm()
        profile_form=UserProfileForm()
    return render(request, 'accounts/signup.html', {'user_form':user_form,'profile_form':profile_form})


class UserDetailView(LoginRequiredMixin, DetailView):
    model=User
    template_name='accounts/user_detail.html'

# class UserDeleteView(LoginRequiredMixin, DeleteView):
#     model=User
#     success_url=reverse_lazy('index')



class UserUpdateView(LoginRequiredMixin, UpdateView):
    model=UserProfile
    fields=['profile_pic']
    template_name='accounts/haha.html'
    # success_url=reverse_lazy('index')
    # need to change it to detail
    # extra_context={'userprofile': UserProfileForm()}

    # def get_success_url(self):
    #     return reverse('accounts:user_detail', kwargs={'pk':self.user.pk})

class UserProfileUpateView(LoginRequiredMixin, UpdateView):
    model=UserProfile
    fields=['profile_pic']

cabsharing/templates/accounts/base_accounts.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <h1></h1>
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

cabsharing/templates/accounts/base_user.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <!-- <link href="https://fonts.googleapis.com/css?family=Monoton&display=swap" rel="stylesheet"> -->

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" style="font-family:'Monoton', cursive; font-size:1.2em;" href="{% url 'index' %}">CAB SHARING</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class='navbar-nav mx-auto'>
      <li class="nav-item active"><a class="nav-link" href="{% url 'bookings:bookings_create' %}">Create</a></li>
      {% if user.is_authenticated %}
      <li class="nav-item active"><a class="nav-link" href="{% url 'bookings:my_bookings' %}">myBookings</a></li>
      {% endif %}

    </ul>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'bookings:feedback' %}">Feedback<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{request.user.username}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:user_detail' pk=user.pk %}">Profile</a>
            <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Logout</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:user_logout' %}">Logout<span class="sr-only">(current)</span></a>
        </li>

        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:user_login' %}">Login<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:user_signup' %}">Sign Up<span class="sr-only">(current)</span></a>
        </li>

        {% endif %}
      </ul>

    </div>
  </nav>

  {% block content %}
  {% endblock %}



  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>
<!-- font-family: 'Monoton', cursive; -->

cabsharing/templates/accounts/feedback.html
{% extends 'accounts/base_user.html' %}
{% load crispy_forms_tags %}

{% block title%}
Feedback
{% endblock %}

{% block content %}
<br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'index' %}"><span aria-hidden="true">×</span></a></button>

      <h1>Feedback</h1>
    </div>
    <div class="card-body">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-success btn-lg">Submit</button>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

cabsharing/templates/accounts/login.html
{% extends 'accounts/base_accounts.html' %}
{% load crispy_forms_tags %}

{% block title %}
Login
{% endblock %}


{% block content %}
<br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'index' %}"><span aria-hidden="true">×</span></a></button>

      <h1>Login</h1>
    </div>
    <div class="card-body">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-success btn-lg">Login</button>
          </div>
          <br>
          <hr>
          <a href="{% url 'accounts:password_reset' %}">forgot password?</a>
          <p class='text-center'>Don't have an account yet? <a href="{% url 'accounts:user_signup' %}">SignUp</a></p>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

cabsharing/templates/accounts/password_change_done.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}
Congratulations
{% endblock %}

{% block content %}
<div class="container" style='width:30rem background-color:rgb() ;'>
  <h3>Your Password has been successfully changed.</h3>
  <h6><a href="{% url 'index' %}">Click</a> here to go back.</h6>
</div>
{% endblock %}

cabsharing/templates/accounts/password_reset_complete.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}
Congratulations
{% endblock %}

{% block content %}
<div class="container" style='width:30rem background-color:rgb() ;'>
  <h3>Your password has been successfully reset.</h3>
  <h6><a href="{% url 'login' %}">Click</a> here to go login.</h6>
</div>
{% endblock %}

cabsharing/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base_accounts.html' %}
{% load crispy_forms_tags %}

{% block title %}
Set Password
{% endblock %}


{% block content %}
<br><br><br>
{% if validlink %}
<div class="container">
  <div class="card">
    <div class="card-header text-center">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'index' %}"><span aria-hidden="true">×</span></a></button>

      <h1>Set password</h1>
    </div>
    <div class="card-body">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-success btn-lg">Save</button>
          </div>
          <br>
          <hr>
          <a href="{% url 'accounts:password_reset' %}">forgot password?</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% else %}
<p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
</p>

{% endif %}
<h3><a href="{% url 'accounts:password_reset_confirm' %}">Click</a> to generate a new link.</h3>
{% endblock %}

cabsharing/templates/accounts/password_reset_done.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}
Congratulations
{% endblock %}

{% block content %}
<div class="container" style='width:30rem background-color:rgb() ;'>
  <h3>A link has been sent to your email-id. Please check!</h3>
  <h6><a href="{% url 'index' %}">Click</a> here to go to the site again.</h6>
</div>
{% endblock %}

cabsharing/templates/accounts/password_reset_email.html
You asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

cabsharing/templates/accounts/password_reset_form.html
{% extends 'accounts/base_accounts.html' %}
{% load crispy_forms_tags %}

{% block title %}
Forgot Password
{% endblock %}


{% block content %}
<br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'accounts:user_login' %}"><span aria-hidden="true">×</span></a></button>

      <h1>Email</h1>
    </div>
    <div class="card-body">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-info btn-lg">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

cabsharing/templates/accounts/signup.html
{% extends 'accounts/base_accounts.html' %}
{% load crispy_forms_tags %}

{% block title %}
Sign Up
{% endblock %}


{% block content %}
<br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'index' %}"><span aria-hidden="true">×</span></a></button>

      <h1>Sign Up</h1>
    </div>
    <div class="card-body">
      <div class="container">
        <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{user_form.username|as_crispy_field}}
            </div>
            <div class="form-group col-md-6 mb-0">
              {{user_form.password|as_crispy_field}}
            </div>
            <div class="form-group col-md-6 mb-0">
              {{user_form.email|as_crispy_field}}
            </div>
            <div class="form-group col-md-6 mb-0">
              {{profile_form.hostel|as_crispy_field}}
            </div>
            <div class="form-group col-md-5-7 mb-0">
              {{profile_form.profile_pic|as_crispy_field}}
            </div>
          </div>
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-primary btn-lg">Sign Up</button>
          </div>
          <hr>
          <p class='text-center'>Already have an account?<a href="{% url 'accounts:user_login' %}">Login</a></p>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}

cabsharing/templates/accounts/user_delete.html
<!-- {% extends 'accounts/base_user.html' %}

{% block title %}
Delete
{% endblock %}

{% block content %}
<div class="container" style='width:30rem background-color:rgb() ;'>
  <form  method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete {{user.username}} ?</h3>
    <input type="submit" value="Delete" class='btn btn-danger btn-lg'>

  </form>

</div>
{% endblock %} -->

cabsharing/templates/accounts/user_detail.html
{% extends 'accounts/base_user.html' %}


{% block title %}
Profile
{% endblock %}


{% block content %}
<br><br><br><br>
<div class="container">
  <div class="card mx-auto" style='width: 30rem;'>
    <img class='card-img-top' src="{{user.userprofile.profile_pic.url}}" alt="none">
    <div class="card-img-overlay">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'index' %}"><span style="text-color:white;" aria-hidden="true">×</span></a></button>

    </div>
    <div class="card-body">
      <div class="card-title text-center">
        <h2>{{user.username}}</h2>
      </div>
      <div class="card-text">
        <h6>Email: {{user.email}}</h6>
        <h6>Hostel: {{user.userprofile.hostel}}</h6>
        <br>
        </div>


    </div>
  </div>
  <br>
  <div class="text-center">
    <!-- <a href="{% url 'accounts:user_update' pk=user.pk %}" class=' btn btn-warning'>Update profile_pic</a> -->
  </div>

</div>
{% endblock %}

cabsharing/templates/accounts/user_update.html
{% extends 'accounts/base_user.html' %}
{% load crispy_forms_tags %}

{% block title%}
Update
{% endblock %}

{% block content %}
<br><br><br>
<div class="container">
  <div class="card">
    <div class="card-header text-center">
      <button type="button" class="close modal-close ml-auto" data-dismiss="modal" aria-label="Close"><a href="{% url 'index' %}"><span aria-hidden="true">×</span></a></button>

      <h1>Update</h1>
    </div>
    <div class="card-body">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
          {% endfor %}
          <div class="text-center">
            <button type="submit" class="btn btn-warning btn-lg">Save</button>
          </div>
          <br>

        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}